# Generated by Django 4.2 on 2023-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothing'),
        ),
    ]
